<?php
/**
 * This is the default virtual host configuration template for Drush Server 
 * running on Mac OSX using the builtin Apache and PHP.
 *
 * Available Variables:
 * - host
 * - port
 * - uri
 * - conf_path
 * - base_path
 * - log_path
 * - doc_root
 * - conf_file
 */
?>
#
# Generated by drush-server.
#
<VirtualHost *:<?php print $port; ?>>
  ServerName "<?php print $host; ?>"
  # TODO: support for ServerAlias

  DocumentRoot "<?php print $doc_root; ?>"
  <Directory "<?php print $doc_root; ?>">
    AllowOverride all
    Order allow,deny
    Allow from all
  </Directory>

</VirtualHost>

